// Code generated by Kitex v0.12.3. DO NOT EDIT.
package linkservice

import (
	server "github.com/cloudwego/kitex/server"
	link "link_shorten_server/link/kitex_gen/link"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler link.LinkService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler link.LinkService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
